spring.application.name=Care

spring.datasource.url=jdbc:postgresql://localhost:5432/care_plus
spring.datasource.username=postgres
spring.datasource.password=SasiEver@0801
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

ai.api.base-url=http://localhost:5000

security.jwt.secret=0111a3885f2a510153b6e911f48032cf34bde473e98609f2f203556203aee1b7
security.jwt.expiration-ms=86400000
security.jwt.cookie-name=CARE_TOKEN
security.jwt.cookie-secure=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.example.care=DEBUG
logging.level.org.springframework.security.config.annotation=ERROR
